name: upn_qr
description: Working with UPN QR code content (for Slovenia). Parse code data.
version: 0.0.4
repository: https://github.com/greymag/dart_upn_qr
issue_tracker: https://github.com/greymag/dart_upn_qr/issues

environment:
  sdk: ^3.0.0

dev_dependencies:
  innim_lint: ^0.4.0
  test: ^1.24.6
dependencies:
  equatable: ^2.0.5
